index:
    path: /
    controller: App\Controller\index::index

inscription:
    path: /inscription
    controller: App\Controller\inscription::start

connexion:
    path: /connexion
    controller: App\Controller\inscription::connect